prepare package to work with live-boot and noble

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,42 +1,49 @@
-#!/bin/bash
+#!/bin/sh
+# postinst script for lliurex-live-fixes.
+#
+# See: dh_installdeb(1).
 
 set -e
 
+# Summary of how this script can be called:
+#        * <postinst> 'configure' <most-recently-configured-version>
+#        * <old-postinst> 'abort-upgrade' <new version>
+#        * <conflictor's-postinst> 'abort-remove' 'in-favour' <package>
+#          <new-version>
+#        * <postinst> 'abort-remove'
+#        * <deconfigured's-postinst> 'abort-deconfigure' 'in-favour'
+#          <failed-install-package> <version> 'removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package.
 
-if  [ "$1" = "configure" ] ; then
+PKG="lliurex-live-fixes"
 
-	PKG="lliurex-live-fixes"
+case "$1" in
+    configure)
 
-	ORIGINAL_MICROCODE_FILE="/usr/share/initramfs-tools/hooks/intel_microcode"
-	DIVERTED_MICROCODE="/usr/share/lliurex-live-fixes/diversions/intel_microcode"
-
-
-	#if [ ! -e "DIVERTED_MICROCODE" ]; then
-	#	dpkg-divert --add --package ${PKG} --rename --divert "$DIVERTED_MICROCODE" "$ORIGINAL_MICROCODE_FILE"
-	#fi
-
-
-	ORIGINAL_MICROCODE_FILE="/usr/share/initramfs-tools/hooks/amd64_microcode"
-	DIVERTED_MICROCODE="/usr/share/lliurex-live-fixes/diversions/amd64_microcode"
-
-
-	#if [ ! -e "DIVERTED_MICROCODE" ]; then
-	#	dpkg-divert --add --package ${PKG} --rename --divert "$DIVERTED_MICROCODE" "$ORIGINAL_MICROCODE_FILE"
-	#fi
-
-
-        ORIGINAL_MYSQL_FILE="/usr/sbin/mysqld"
+	ORIGINAL_MYSQL_FILE="/usr/sbin/mysqld"
         DIVERTED_MYSQL="/usr/share/lliurex-live-fixes/diversions/mysqld"
 
 
         if [ ! -e "DIVERTED_MYSQL" ]; then
                 dpkg-divert --add --package ${PKG} --rename --divert "$DIVERTED_MYSQL" "$ORIGINAL_MYSQL_FILE"
 		ln -s /bin/true /usr/sbin/mysqld
-        fi
 
-fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument '$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
 exit 0
-
diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,42 +1,27 @@
-#!/bin/bash
+#!/bin/sh
+# prerm script for lliurex-live-fixes.
+#
+# See: dh_installdeb(1).
 
 set -e
 
+# Summary of how this script can be called:
+#        * <prerm> 'remove'
+#        * <old-prerm> 'upgrade' <new-version>
+#        * <new-prerm> 'failed-upgrade' <old-version>
+#        * <conflictor's-prerm> 'remove' 'in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> 'deconfigure' 'in-favour'
+#          <package-being-installed> <version> 'removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package.
 
-if [ "$1" = "remove" ] ; then
+PKG="lliurex-live-fixes"
 
-	PKG="lliurex-live-fixes"
-
-	ORIGINAL_MICROCODE_FILE="/usr/share/initramfs-tools/hooks/intel_microcode"
-	DIVERTED_MICROCODE="/usr/share/lliurex-live-fixes/diversions/intel_microcode"
-	
-	#if [ -e "$DIVERTED_MICROCODE" ]; then
-	#	if [ -e $ORIGINAL_MICROCODE_FILE ]; then
-	#		rm $ORIGINAL_MICROCODE_FILE || true
-	#	fi
-        #       dpkg-divert --remove --package ${PKG} --rename --divert "$DIVERTED_MICROCODE" "$ORIGINAL_MICROCODE_FILE"
-		
-
-        #fi
-
-	ORIGINAL_MICROCODE_FILE="/usr/share/initramfs-tools/hooks/amd64_microcode"
-	DIVERTED_MICROCODE="/usr/share/lliurex-live-fixes/diversions/amd64_microcode"
-	
-	#if [ -e "$DIVERTED_MICROCODE" ]; then
-
-	#	if [ -e $ORIGINAL_MICROCODE_FILE ]; then
-        #                rm $ORIGINAL_MICROCODE_FILE || true
-        #        fi
-
-        #        dpkg-divert --remove --package ${PKG} --rename --divert "$DIVERTED_MICROCODE" "$ORIGINAL_MICROCODE_FILE"
-		
-
-        #fi
-
-
-        ORIGINAL_MYSQL_FILE="/usr/sbin/mysqld"
+case "$1" in
+    remove)
+	ORIGINAL_MYSQL_FILE="/usr/sbin/mysqld"
         DIVERTED_MYSQL="/usr/share/lliurex-live-fixes/diversions/mysqld"
-
 
         if [ ! -e "DIVERTED_MYSQL" ]; then
 
@@ -52,16 +37,26 @@ if [ "$1" = "remove" ] ; then
 	N4D_ONESHOT_DIR="/etc/n4d/one-shot/"
 	PACKAGE_ONESHOTS_DIR="/usr/share/lliurex-live-fixes/n4d-oneshots"
 
-	if [ ! -d $N4D_ONESHOT_DIR ]; then
-	
-		mkdir -p $N4D_ONESHOT_DIR || true
-
-	fi
+	mkdir -p $N4D_ONESHOT_DIR || true
 
 	cp "$PACKAGE_ONESHOTS_DIR"/* $N4D_ONESHOT_DIR || true
 
+    ;;
+    upgrade|deconfigure)
+    ;;
 
-fi
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument '$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 #DEBHELPER#
 
 exit 0
